@PdfCompressionService_HostAddress = http://localhost:7777

###

# Compress PDF
POST {{PdfCompressionService_HostAddress}}/compressPdf
Content-Type: multipart/form-data

file: < /path/to/your/sample.pdf